name: build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
            9.0.x
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: dotnet build ./src/ZNetCS.AspNetCore.Logging.EntityFrameworkCore/ZNetCS.AspNetCore.Logging.EntityFrameworkCore.csproj --configuration Release
      - name: Test with dotnet for .NET 6.0
        run: dotnet test ./test/ZNetCS.AspNetCore.Logging.EntityFrameworkCoreTest/ZNetCS.AspNetCore.Logging.EntityFrameworkCoreTest.csproj --configuration Release
